default: &default
  adapter: postgresql
  encoding: unicode

local_default: &local_default
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres")  %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres")  %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  

development:
  <<: *local_default
  database: course_craft_development

test:
  <<: *local_default
  database: course_craft_test

production:
  <<: *default
  # url: <%= ENV.fetch("DATABASE_URL", Rails.application.credentials.database_url) %>
  database: course_craft_production
  username: course_craft
  password: <%= ENV["COURSE_CRAFT_DATABASE_PASSWORD"] %>
